### ISSUE TITLE
Add a view mode for object properties

### ISSUE THREAD

**Issue by claustres** [kalisio/kCore#131]
Similar to what is provided by the editor/form system but to only display information (no edition), typical use case is https://github.com/kalisio/kMap/issues/66.

Should provide:
* [x] high level KViewer/KModalViewer components to easily create read-only views of objects (similar to KEditor/KModalEditor for edition)
* [x] KView component which aggregates different field displays (similar to KForm for edition)
* [x] base viewer mixin to ease the implementation of custom viewers (similar to base editor mixin for edition)
* [x] KXXXViewField components to create read-only displays suited to different data types
* [x] schema proxy mixin to provide the capability to give the schenaName by the parent component

One open question is if we can reuse existing field components and simply add a view mode inside.

**Comment by claustres** [comment]
Work already prototyped in k-viewer branch (kApp), to be integrated.

**Comment by cnouguier** [comment]
The adopted approach works well but KXXXViewField should be enhanced in the future
