### ISSUE TITLE
Extend fields

### ISSUE THREAD

**Issue by claustres** [kalisio/kCore#23]
* [x] KItemField
* [x] KIconField
* [x] KChipsWithIconField
* [x] KDateTime
* [x] KLocation
* [x] KFileInput
* [ ] KEditor (based on new QEditor)

**Comment by cnouguier** [comment]
Waiting for Quasar 0.15 to be released in order to use the KEditor component. 
Other possible solutions are to integrate such solutions as:

- https://github.com/davidroyer/vue2-editor
- https://github.com/hifarer/vueditor

**Comment by claustres** [comment]
Added a field to be able to import a text file on the client side, eg CSV.

**Comment by claustres** [comment]
Closing for now, will reopen dedicated issue when required.
