### ISSUE TITLE
Non members query is no more working

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kCore#28]
Since the authorisations on, the query used to list the users who do not belong to a given organisation does not work.
{organisations._id: {$nin: ["5a351d70d2c4062890232a63"]}, $select: ["profile"],…}

**Comment by claustres** [comment]
Seems to work on my tests, don't know really what was the problem, more precise example to reproduce ?

**Comment by cnouguier** [comment]
Indeed, it works.
