### ISSUE TITLE
Check whether the email entered when registrating already exist

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kCore#3]
When registering a new user, the system must check whether the entered email exist or not.

**Comment by cnouguier** [comment]
One possible approach could be to use asynchronous validation capabilities.
See: https://github.com/epoberezkin/ajv#asynchronous-validation

**Comment by claustres** [comment]
We should use the operation provided by the Feathers auth service: https://docs.feathersjs.com/api/authentication/local-management.html#local-authentication-management.

**Comment by claustres** [comment]
Added hook in kNotify
