### ISSUE TITLE
Tags? Perspectives?

### ISSUE THREAD

**Issue by musicformellons** [kalisio/kCore#73]
What are tags? What are perspectives?

**Comment by claustres** [comment]
Thanks for your interest, i am afraid docs are not yet completed. Some information is provided here: https://kalisio.gitbooks.io/kalisio/api/#data-model and https://kalisio.gitbooks.io/kalisio/architecture/DATAMODEL.html#tag-data-model. You can add/remove tags to objects like users. A tag can be associated to a SNS topic to notify all users with a given tag.

**Comment by musicformellons** [comment]
Ah, yeah, that's more clear to  me now, thanks! The permissions are part of the 'scope' which is on the user object. Are these also 'perspectives'...?

**Comment by claustres** [comment]
No because we almost always require it to know what the user is allowed to do.

**Comment by musicformellons** [comment]
Ok!
