### ISSUE TITLE
Create a time controller

### ISSUE THREAD

**Issue by claustres** [kalisio/kCore#87]
The controller should be generic enough to be used in different contexts. As input properties it will have:
* a start date/time
* a end date/time
* a time step indicating the granularity of the slider from the user perspective

It should be responsive and include a way to switch between UTC/local time display.

See https://www.windy.com/ as a reference.

**Comment by claustres** [comment]
In a first version the tick could be fixed to a day granularity, while timeslider granularity is per hour.

**Comment by leob** [comment]
List of remaining bugs and enhancements:

- Dragging the pointer: it would be good if the pointer is also 'tracked' if you "drag" the mouse below/above the pointer
- Move the pointer when clicking on the "bar" (with animation)
- Make the "touch area" of the bar wider
- Locale/timezone support
- Windytv: shows the time label as you hover the mouse over the bar
- Windytv: shows a vertical bar where "now" is
- Implement a player button (separate component)
- What about touch devices?

**Comment by leob** [comment]
Bug: when the app starts with the side panel(s) already open and the user closes the side panel(s) then the timeline controller seems to be "broken" (tracking doesn't work anymore).

**Comment by claustres** [comment]
To be more flexible I suggest the display format to be an input option of the time controller instead of hard-coded value like [here](https://github.com/kalisio/kCore/blob/master/src/client/components/time/KTimePointer.vue#L61), [here](https://github.com/kalisio/kCore/blob/master/src/client/components/time/KTimeInterval.vue#L61) or [here](https://github.com/kalisio/kCore/blob/master/src/client/components/time/KTimeIndicator.vue#L50). In that case the `type` option will not be required anymore and be replaced by it. We could split the option in different flavors like:
```
intervalFormat: 'XXX',
pointerFormat: 'XXX',
indicatorFormat: 'XXX'
```
If we want to be even more flexible like changing the format depending on the screen size maybe we can optionally pass a format function like this:
```
displayFormat: (time, type, displayOptions) => {
  switch (type) {
    case 'interval': ...if (displayOptions.width > xxx)...
    case 'pointer': ...
    case 'indicator': ...
  }
}
```
Let me know what you think but I am afraid depending on the app hard-coded time format will not be suitable.

**Comment by leob** [comment]
Okay, fair enough, yes I agree that hard-coded values should preferably be avoided ... on the other hand, in a few cases I'm dynamically computing the way I display the info (for instance when there's less space available then I display the "interval" labels in a more compressed way, like Windy also does) ...

Let me see if I can at least make the time display configurable (so instead of having AM/PM hardcoded as the format)

**Comment by leob** [comment]
Done, extracted all of the time formatting/interval logic into a few functions inside an object that I'm passing as a prop, this was pretty simple ... actually, it would be pretty trivial to extract the last "time specific" stuff from the timecontroller and make it a completely generic "range controller".
